name: wikiquote
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/earendil06/wikiquote-dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.1
  html: ^0.14.0+3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
